version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to install"
  build:
    commands:
      - echo "Zipping deployment package"
      - zip -r deploy.zip deploy/index.html deploy/scripts/ deploy/appspec.yml

artifacts:
  files:
    - deploy.zip
